api/urls.py
from django.urls import path

from api.views import ProductListAPIView, ProductRetrieveAPIView

app_name = 'api'

urlpatterns = [
    path('products/', ProductListAPIView.as_view()),
    path('products/<int:pk>/', ProductRetrieveAPIView.as_view()),
]

posts/urls.py
from django.urls import path

from posts.views import PostsListView, PostDetailView, CommentCreateView

app_name = 'posts'

urlpatterns = [
    path('', PostsListView.as_view(), name='list'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('<int:pk>comment/', CommentCreateView.as_view(), name='comment'),
]

six_module/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('pages.urls', namespace='pages')),
    path('blog/', include('posts.urls', namespace='posts')),
    path('api/', include('api.urls', namespace='api')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('profile/', include('users.urls', namespace='profile')),
    path('products/', include('products.urls', namespace='products')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <title>Drophunt</title>
    <meta name="description" content="">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/plugins.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block extra_css %}
    {% endblock %}

</head>

<body>

{% include 'layouts/header.html' %}

{% block content %}

{% endblock %}

{% include 'layouts/footer.html' %}

<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block extra_js %}
{% endblock %}


</body>
</html>

templates/layouts/footer.html
{% load static %}
<footer class="footer_widgets">
    <div class="footer_top">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="widgets_container contact_us">
                        <div class="footer_logo">
                            <a href="#"><img src="{% static 'img/logo/logo.png' %}" alt=""></a>
                        </div>
                        <div class="footer_contact">
                            <p>John draw real poor on call my from. May she mrs furnished discourse extremely. Ask doubt
                                noisy shade guest Lose away off why half led have near bed. At engage simple father of
                                period others except</p>
                            <p>Ask doubt noisy shade guest Lose away off why half led have near bed. At engage simple
                                father of period others except</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6">
                    <div class="widgets_container widget_menu">
                        <h3>Information</h3>
                        <div class="footer_menu">
                            <ul>
                                <li><a href="about.html">About Us</a></li>
                                <li><a href="blog.html">Delivery Information</a></li>
                                <li><a href="contact.html">Privacy Policy</a></li>
                                <li><a href="services.html">Terms & Conditions</a></li>
                                <li><a href="#">Returns</a></li>
                                <li><a href="#">Gift Certificates</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6">
                    <div class="widgets_container widget_menu">
                        <h3>My Account</h3>
                        <div class="footer_menu">
                            <ul>
                                <li><a href="#">My Account</a></li>
                                <li><a href="#">Order History</a></li>
                                <li><a href="wishlist.html">Wish List</a></li>
                                <li><a href="#">Newsletter</a></li>
                                <li><a href="#">Affiliate</a></li>
                                <li><a href="faq.html">International Orders</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="widgets_container newsletter">
                        <h3>Follow Us</h3>
                        <div class="footer_social_link">
                            <ul>
                                <li><a class="facebook" href="#" title="Facebook"><i class="fa fa-facebook"></i></a>
                                </li>
                                <li><a class="twitter" href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a class="instagram" href="#" title="instagram"><i class="fa fa-instagram"></i></a>
                                </li>
                                <li><a class="linkedin" href="#" title="linkedin"><i class="fa fa-linkedin"></i></a>
                                </li>
                                <li><a class="rss" href="#" title="rss"><i class="fa fa-rss"></i></a></li>
                            </ul>
                        </div>
                        <div class="subscribe_form">
                            <h3>Join Our Newsletter Now</h3>
                            <form id="mc-form" class="mc-form footer-newsletter">
                                <input id="mc-email" type="email" autocomplete="off"
                                       placeholder="Your email address..."/>
                                <button id="mc-submit">Subscribe!</button>
                            </form>
                            <!-- mailchimp-alerts Start -->
                            <div class="mailchimp-alerts text-centre">
                                <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                                <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                                <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                            </div><!-- mailchimp-alerts end -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer_bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6">
                    <div class="copyright_area">
                        <p><a href="templateshub.net">Templates Hub</a></p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="footer_payment text-right">
                        <a href="#"><img src="{% static 'img/icon/payment.png' %}" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/layouts/posts_block.html
{% load my_tags %}
{% load static %}

<a href="{% url 'posts:detail' pk=post.pk %}">
    <article class="single_blog mb-60">
        <figure>
            <div class="blog_thumb">
                <img src="{{ post.image.url }}">
            </div>
            <figcaption class="blog_content">
                <h3>{{ post.title }}</h3>
                <div class="blog_meta">
                    <span class="author">Posted by : <a href="#">{{ post.author }}</a> / </span>
                    <span class="post_date">On : <a
                            href="#">{{ post.created_at|date:'F d, Y' }}</a></span>
                </div>
                <footer class="readmore_button">
                    <a href="{% url 'posts:detail' pk=post.pk %}">Read more</a>
                </footer>
            </figcaption>
        </figure>
    </article>
</a>

templates/layouts/product_block.html
{% load my_tags %}
{% load static %}

<div class="single-tranding">
    <a href="{% url 'products:detail' pk=product.pk %}">
        <div class="tranding-pro-img">
            <img src="{{ product.image.url }}">
        </div>
        <div class="tranding-pro-title">
            <h3>{{ product.title }}</h3>
            <h4>Drone</h4>
        </div>
        <div class="tranding-pro-price">
            <div class="price_box">
                <span class="current_price">${{ product.real_price }}</span>
                {% if product.is_discount %}
                    <span class="old_price">${{ product.price }}</span>
                {% endif %}
            </div>
        </div>
    </a>
</div>