api/urls.py
from django.urls import path

from api.views import ProductListAPIView, ProductRetrieveAPIView

app_name = 'api'

urlpatterns = [
    path('products/', ProductListAPIView.as_view()),
    path('products/<int:pk>/', ProductRetrieveAPIView.as_view()),
]

orders/urls.py
from django.urls import path

from orders.views import OrderCreateView, OrderHistoryListView

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='create'),
    path('history/', OrderHistoryListView.as_view(), name='history'),
]

posts/urls.py
from django.urls import path

from posts.views import PostsListView, PostDetailView, CommentCreateView

app_name = 'posts'

urlpatterns = [
    path('', PostsListView.as_view(), name='list'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('<int:pk>comment/', CommentCreateView.as_view(), name='comment'),
]

products/urls.py
from django.urls import path

from products.views import ProductsDetailView, ProductsListView, WishlistListView, add_wishlist, add_to_cart, \
    CartListView

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='list'),
    path('wishlist/', WishlistListView.as_view(), name='wishlist'),
    path('wishlist/<int:pk>/', add_wishlist, name='add-wishlist'),
    path('cart/', CartListView.as_view(), name='cart-list'),
    path('cart/<int:pk>/', add_to_cart, name='add-to-cart'),
    path('<int:pk>/', ProductsDetailView.as_view(), name='detail'),
]

six_module/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('pages.urls', namespace='pages')),
    path('blog/', include('posts.urls', namespace='posts')),
    path('api/', include('api.urls', namespace='api')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('profile/', include('users.urls', namespace='profile')),
    path('products/', include('products.urls', namespace='products')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


UserModel = get_user_model()


class CategoryModel(models.Model):
    title = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class ColorModel(models.Model):
    code = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = 'color'
        verbose_name_plural = 'colors'


class ProductModel(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    image = models.ImageField(upload_to='products')
    price = models.FloatField()
    discount = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MinValueValidator(0),
            MaxValueValidator(100)
        ]
    )
    short_description = models.TextField()
    long_description = RichTextUploadingField()
    category = models.ForeignKey(
        CategoryModel,
        on_delete=models.PROTECT,
        related_name='products'
    )
    real_price = models.FloatField(default=0)
    colors = models.ManyToManyField(ColorModel, related_name='products')
    wishlist = models.ManyToManyField(UserModel, related_name='wishlist')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    @staticmethod
    def get_from_cart(request):
        cart = request.session.get('cart', [])
        return ProductModel.objects.filter(
            pk__in=cart
        )

    def is_discount(self):
        return self.discount != 0

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'


class ProductImageModel(models.Model):
    product = models.ForeignKey(ProductModel, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products')

    def __str__(self):
        return self.product.title

    class Meta:
        verbose_name = 'product image'
        verbose_name_plural = 'product images'

products/forms.py
from django import forms

from products.models import ColorModel


class ColorModelForm(forms.ModelForm):
    class Meta:
        model = ColorModel
        fields = '__all__'
        widgets = {
            'code': forms.TextInput(attrs={
                'type': 'color'
            })
        }

products/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Min, Max
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import DetailView, ListView, TemplateView

from products.models import ProductModel, CategoryModel, ColorModel


class ProductsListView(ListView):
    template_name = 'products.html'
    paginate_by = 3

    def get_queryset(self):
        qs = ProductModel.objects.order_by('-pk')
        q = self.request.GET.get('q')
        cat = self.request.GET.get('cat')
        color = self.request.GET.get('color')
        price = self.request.GET.get('price')

        if q:
            qs = qs.filter(title__icontains=q)

        if cat:
            qs = qs.filter(category_id=cat)

        if color:
            qs = qs.filter(colors__id=color)

        if price:
            price_from, price_to = price.split(';')
            qs = qs.filter(real_price__gte=price_from, real_price__lte=price_to)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['categories'] = CategoryModel.objects.all()
        context['colors'] = ColorModel.objects.all()

        min_price, max_price = ProductModel.objects.aggregate(
            Min('real_price'),
            Max('real_price')
        ).values()

        context['min_price'], context['max_price'] = int(min_price), int(max_price)
        return context


class ProductsDetailView(DetailView):
    template_name = 'product-details.html'
    model = ProductModel


class WishlistListView(LoginRequiredMixin, ListView):
    template_name = 'wishlist.html'

    def get_queryset(self):
        return self.request.user.wishlist.all()


class CartListView(ListView):
    template_name = 'cart.html'

    def get_queryset(self):
        return ProductModel.get_from_cart(self.request)


class CartHeaderListView(ListView):
    template_name = 'layouts/header.html'

    def get_queryset(self):
        return ProductModel.get_from_cart(self.request)


@login_required
def add_wishlist(request, pk):
    product = get_object_or_404(ProductModel, pk=pk)
    user = request.user
    if user in product.wishlist.all():
        product.wishlist.remove(user)
    else:
        product.wishlist.add(user)

    return redirect(request.GET.get('next', '/'))


def add_to_cart(request, pk):
    cart = request.session.get('cart', [])

    if pk in cart:
        cart.remove(pk)
    else:
        cart.append(pk)

    request.session['cart'] = cart
    print(cart)

    return redirect(request.GET.get('next', '/'))

templates/blog-details.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <div class="blog_details mt-60">
        <div class="container">
            <div class="row">

                <div class="col-lg-9 col-md-12">
                    <!--blog grid area start-->
                    <div class="blog_wrapper">
                        <article class="single_blog">
                            <figure>
                                <div class="post_header">
                                    <h3 class="post_title">{{ object.title }}</h3   >
                                    <div class="blog_meta">
                                        <span class="author">Posted by : <a href="#">{{ object.author }}</a> / </span>
                                        <span class="post_date"><a
                                                href="#">{{ object.created_at|date:'F d, Y' }}</a></span>
                                    </div>
                                </div>
                                <div class="blog_thumb">
                                    <a href="#"><img src="{{ object.banner.url }}" alt=""></a>
                                </div>
                                <figcaption class="blog_content">
                                    <div class="post_content">
                                        {{ object.content|safe }}
                                    </div>
                                    <div class="entry_content">
                                        <div class="post_meta">
                                            <span>Tags: </span>
                                            {% for tag in object.tags.all %}
                                                <span><a
                                                        href="{% url 'posts:list' %}?tag={{ tag.title }}">#{{ tag.title }} </a></span>
                                            {% endfor %}
                                        </div>

                                        <div class="social_sharing">
                                            <p>share this post:</p>
                                            <ul>
                                                <li><a href="#" title="facebook"><i class="fa fa-facebook"></i></a></li>
                                                <li><a href="#" title="twitter"><i class="fa fa-twitter"></i></a></li>
                                                <li><a href="#" title="pinterest"><i class="fa fa-pinterest"></i></a>
                                                </li>
                                                <li><a href="#" title="google+"><i class="fa fa-google-plus"></i></a>
                                                </li>
                                                <li><a href="#" title="linkedin"><i class="fa fa-linkedin"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </figcaption>
                            </figure>
                        </article>
                        <div class="comments_box">
                            <h3 id="comment">{{ object.comments.count }} Comments </h3>
                            {% for comment in object.get_comments %}
                                <div class="comment_list">
                                    <div class="comment_content">
                                        <div class="comment_meta">
                                            <h5><a href="#">{{ comment.author }}</a></h5>
                                            <span>{{ comment.created_at|date:'M d, Y at H:m' }}</span>
                                        </div>
                                        <p>{{ comment.comment }}</p>
                                        <div class="comment_reply">
                                            <a href="#">Reply</a>
                                        </div>
                                    </div>

                                </div>
                            {% endfor %}
                        </div>
                        <div class="comments_form">
                            <h3>Leave a Reply </h3>
                            <p>Your email address will not be published. Required fields are marked *</p>
                            <form method="POST" action="{% url 'posts:comment' pk=object.pk %}#comment">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-12">
                                        <label for="review_comment">Comment </label>
                                        <textarea name="comment" id="review_comment"></textarea>
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <label for="author">Name</label>
                                        <input name="name" id="author" type="text">

                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <label for="email">Email </label>
                                        <input name="email" id="email" type="email">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <label for="website">Phone </label>
                                        <input name="phone" id="website" type="text">
                                    </div>
                                </div>
                                <button class="button" type="submit">Post Comment</button>
                            </form>
                        </div>
                    </div>
                    <!--blog grid area start-->
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/cart.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <div class="shopping_cart_area mt-60">
        <div class="container">
            <form action="#">
                <div class="row">
                    <div class="col-12">
                        <div class="table_desc">
                            <div class="cart_page table-responsive">
                                <table>
                                    <thead>
                                    <tr>
                                        <th class="product_thumb">Image</th>
                                        <th class="product_name">Product</th>
                                        <th class="product-price">Price</th>
                                        <th class="product_quantity">Quantity</th>
                                        <th class="product_total">Total</th>
                                        <th class="product_remove">Remove</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for product in object_list %}
                                        <tr>
                                            <td class="product_thumb">
                                                <a href="#">
                                                    <img src="{{ product.image.url }}" alt="">
                                                </a>
                                            </td>
                                            <td class="product_name">
                                                <a href="#">{{ product.title }}</a>
                                            </td>
                                            <td class="product-price">${{ product.real_price }}</td>
                                            <td class="product_quantity">
                                                <label>Quantity</label>
                                                <input min="1" max="100" value="1" type="number">
                                            </td>
                                            <td class="product_total">${{ product.real_price }}</td>
                                            <td class="product_remove">
                                                <a href="{% url 'products:add-to-cart' pk=product.pk %}?next={{ request.path }}?{{ request.GET.urlencode }}">
                                                    <i class="ion-android-close"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!--coupon code area start-->
                <div class="coupon_area">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="coupon_code left">
                                <h3>Coupon</h3>
                                <div class="coupon_inner">
                                    <p>Enter your coupon code if you have one.</p>
                                    <input placeholder="Coupon code" type="text">
                                    <button type="submit">Apply coupon</button>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="coupon_code right">
                                <h3>Cart Totals</h3>
                                <div class="coupon_inner">
                                    <div class="cart_subtotal">
                                        <p>Subtotal</p>
                                        <p class="cart_amount">${% cart_price request %}</p>
                                    </div>
                                    <div class="cart_subtotal ">
                                        <p>Shipping</p>
                                        <p class="cart_amount"><span>Flat Rate:</span> ${% cart_price request %}</p>
                                    </div>
                                    <a href="#">Calculate shipping</a>

                                    <div class="cart_subtotal">
                                        <p>Total</p>
                                        <p class="cart_amount">${% cart_price request %}</p>
                                    </div>
                                    <div class="checkout_btn">
                                        <a href="{% url 'orders:create' %}">Proceed to Checkout</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--coupon code area end-->
            </form>
        </div>
    </div>
{% endblock %}

templates/history.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <div class="shopping_cart_area mt-60">
        <div class="container">
            <form action="#">
                <div class="row">
                    <div class="col-12">
                        <div class="table_desc">
                            <div class="cart_page table-responsive">
                                <table>
                                    <thead>
                                    <tr>
                                        <th class="product_thumb">Image</th>
                                        <th class="product_name">Product</th>
                                        <th class="product-price">Price</th>
                                        <th class="product_quantity">Quantity</th>
                                        <th class="product_total">Total</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for order in object_list %}
                                        <tr>
                                            <td class="product_thumb">
                                                <a href="#">
                                                    <img src="{% static 'img/s-product/product.jpg' %}" alt="">
                                                </a>
                                            </td>
                                            <td class="product_name">
                                                <a href="#">{{ order.title }}</a>
                                            </td>
                                            <td class="product-price">${{ order.price }}</td>
                                            <td class="product_quantity">
                                                <label>Quantity</label>
                                                <input min="1" max="100" value="1" type="number">
                                            </td>
                                            <td class="product_total">${{ order.price }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!--coupon code area start-->
                <div class="coupon_area">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <div class="coupon_code right">
                                <h3>Cart Totals</h3>
                                <div class="coupon_inner">
                                    <div class="cart_subtotal">
                                        <p>Subtotal</p>
                                        <p class="cart_amount">${% cart_price request %}</p>
                                    </div>
                                    <div class="cart_subtotal ">
                                        <p>Shipping</p>
                                        <p class="cart_amount"><span>Flat Rate:</span> ${% cart_price request %}</p>
                                    </div>
                                    <a href="#">Calculate shipping</a>

                                    <div class="cart_subtotal">
                                        <p>Total</p>
                                        <p class="cart_amount">${% cart_price request %}</p>
                                    </div>
                                    <div class="checkout_btn">
                                        <a href="{% url 'orders:create' %}">Proceed to Checkout</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--coupon code area end-->
            </form>
        </div>
    </div>
{% endblock %}

templates/product-details.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load my_tags %}
{% block extra_css %}
    <style>
        .shop__sidebar__color {
            padding-top: 15px;
        }

        .shop__sidebar__color label {
            height: 30px;
            width: 30px;
            border-radius: 50%;
            position: relative;
            margin-right: 10px;
            display: inline-block;
            margin-bottom: 10px;
            cursor: pointer;
        }

        .shop__sidebar__color label.c-1 {
            background: #0b090c;
        }

        .shop__sidebar__color label.c-2 {
            background: #20315f;
        }

        .shop__sidebar__color label.c-3 {
            background: #f1af4d;
        }

        .shop__sidebar__color label.c-4 {
            background: #636068;
        }

        .shop__sidebar__color label.c-5 {
            background: #57594d;
        }

        .shop__sidebar__color label.c-6 {
            background: #e8bac4;
        }

        .shop__sidebar__color label.c-7 {
            background: #d6c1d7;
        }

        .shop__sidebar__color label.c-8 {
            background: #ed1c24;
        }

        .shop__sidebar__color label.c-9 {
            background: #ffffff;
        }

        .shop__sidebar__color label:after {
            position: absolute;
            left: -3px;
            top: -3px;
            height: 36px;
            width: 36px;
            border: 1px solid #e5e5e5;
            content: "";
            border-radius: 50%;
        }

        .shop__sidebar__color label input {
            position: absolute;
            visibility: hidden;
        }
    </style>
{% endblock %}

{% block content %}
    <!--product details start-->
    <div class="product_details mt-60 mb-60">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="product-details-tab">
                        <div id="img-1" class="zoomWrapper single-zoom">
                            <a href="#">
                                <img id="zoom1" src="{{ object.image.url }}"
                                     data-zoom-image="{{ object.image.url }}" alt="big-1">
                            </a>
                        </div>
                        <div class="single-zoom-thumb">
                            <ul class="s-tab-zoom owl-carousel single-product-active" id="gallery_01">
                                {% for i in object.images.all %}
                                    <li>
                                        <a href="#" class="elevatezoom-gallery active" data-update=""
                                           data-image="{{ i.image.url }}"
                                           data-zoom-image="{{ i.image.url }}">
                                            <img src="{{ i.image.url }}" alt="zo-th-1"/>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="product_d_right">
                        <form action="#">

                            <h1>{{ product.title }}</h1>
                            <div class=" product_ratting">
                                <ul>
                                    <li><a href="#"><i class="fa fa-star"></i></a></li>
                                    <li><a href="#"><i class="fa fa-star"></i></a></li>
                                    <li><a href="#"><i class="fa fa-star"></i></a></li>
                                    <li><a href="#"><i class="fa fa-star"></i></a></li>
                                    <li><a href="#"><i class="fa fa-star"></i></a></li>
                                    <li class="review"><a href="#"> (250 reviews) </a></li>
                                </ul>

                            </div>
                            <div class="price_box">
                                <span class="current_price">${{ object.real_price }}</span>
                                <span class="old_price">${% if object.is_discount %}
                                    {{ object.price }}{% endif %}</span>

                            </div>
                            <div class="product_desc">
                                <p>{{ object.short_description }}</p>
                            </div>
                            <div class="shop__sidebar__color">
                                <h3>Color</h3>
                                <ul>
                                    {% for color in object.colors.all %}
                                        <label style="background: {{ color.code }}">
                                            <input value="{{ color.code }}" name="color" type="radio">
                                        </label>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="product_variant quantity">
                                <label>quantity</label>
                                <input min="1" max="100" value="1" type="number">
                                <a href="{% url 'products:add-to-cart' pk=object.pk %}?next={{ request.path }}?{{ request.GET.urlencode }}">
                                    {% if object|in_cart:request %}
                                        <button class="button" type="button">remove from cart</button>
                                    {% else %}
                                        <button class="button" type="button">add to cart</button>
                                    {% endif %}
                                </a>
                                <a href="{% url 'products:add-wishlist' pk=object.pk %}?next={{ request.path }}?{{ request.GET.urlencode }}">
                                    {% if object|in_wishlist:request %}
                                        <button class="button" type="button">remove from wishlist</button>
                                    {% else %}
                                        <button class="button" type="button">add to wishlist</button>
                                    {% endif %}
                                </a>
                            </div>
                            <div class="product_meta">
                                <span>Category: <a href="#">{{ object.category.title }}</a></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--product details end-->

    <!--product info start-->
    <div class="product_d_info mb-60">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="product_d_inner">
                        <div class="product_info_button">
                            <ul class="nav">
                                <li>
                                    <a class="active" href="#info" aria-controls="info" aria-selected="false">Description</a>
                                </li>
                            </ul>
                        </div>
                        <div class="tab-content">
                            <div class="tab-pane fade show active" id="info">
                                <div class="product_info_content">
                                    <p>{{ object.long_description|safe }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--product info end-->
{% endblock %}

templates/services.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>